# Codecov settings
# After modifying this file, you can validate it, see https://api.codecov.io/validate

codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  # define the colour bar limits here (red...green)
  range: "75...100"

  # diff type
  status:
    project:
      default:
        # fail if coverage below this:
        target: '85%'
        # fail if coverage drops by this much:
        threshold: '2%'
    patch:
      default:
        target: '85%'

# turn off comments to pull requests
comment: false
